org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true

mod_id=glowgoo
mod_name=Glow Goo
mod_version=1.0.0
mod_group=net.crossface22.glowgoo
mod_authors=CrossFace22
mod_description=Adds a throwable sticky glowing goo that clings to blocks and lights the area.
license=All Rights Reserved

minecraft_version=1.21.11
java_version=21
neoforge_version=21.11.32-beta
moddevgradle_version=2.0.140
